# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules
      run: |
        git submodule update --init --recursive
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install pyinstaller
    - name: PyInstaller
      run: |
        pyinstaller arrayanalysis.spec
        cp ui_array_analysis.ui ./dist/arrayanalysis/
    - name: Archive built module
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: arrayanalysis_linux
        path: ./dist/arrayanalysis
